### ISSUE TITLE
Chart repos are unavailable

### ISSUE THREAD

**Issue by omerozery** [rancher/server-chart#1]
Chart repos (https://jgreat.github.io/helm-rancher-server/charts or https://releases.rancher.com/server-charts) are unavailable

**Comment by jgreat** [comment]
Sorry this is a work in progress.  Will close this when we are ready for this to be live.

**Comment by jgreat** [comment]
[Documentation](https://rancher.com/docs/rancher/v2.x/en/installation/ha/) for installs with the helm chart is up and repo is live.
