### ISSUE TITLE
Error deploying chart on GKE (evaluating ingress spec)

### ISSUE THREAD

**Issue by hans-d** [rancher/server-chart#23]
Ingres sevice reports on GKE: `Error during sync: error while evaluating the ingress spec: service "rancher/rancher" is type "ClusterIP", expected "NodePort" or "LoadBalancer"`

Manual updating the created service rancher/rancher to be type NodePort resolves this

1. have GKE cluster
2. deploy helmchart (optionally do some value updates)
3. check GKE dashboard, and notice the rancher ingress stays in state "creating"
4. Show detail of said ingress and see the error

**Comment by deniseschannon** [comment]
Moved this to our Rancher repo as we are closing the ability to open issues in this repo. 

https://github.com/rancher/rancher/issues/16061
