### ISSUE TITLE
Error deploying on GKE -  getting keypair for CA issuer

### ISSUE THREAD

**Issue by hans-d** [rancher/server-chart#24]
After (manually fixing #23) and having the the tls value of rancher (`ingress.tls.source: rancher`), the ingress controller stays on creating saying `Error getting keypair for CA issuer: secret "tls-rancher" not found`

cert-manager is installed

**Comment by deniseschannon** [comment]
Moved this to our Rancher repo as we are closing the ability to open issues in this repo.

https://github.com/rancher/rancher/issues/16063
