### ISSUE TITLE
upgrade or install with privateCA=true option results in failed install

### ISSUE THREAD

**Issue by cola4u** [rancher/server-chart#33]
I tried both upgrading 2 existing Rancher installs:

1.  A 2.0.8 rancher install, setup with the helm chart - the upgrade gives the error message below
2. A 2.0.8 rancher install, setup with rke and AddOns - went through the upgrade process which meant removing the old add-ons and installing rancher anew using helm.  The same result as below

# helm upgrade rancher rancher-stable/rancher \
>   --set hostname=whatever.tls.domain.name \
>   --set ingress.tls.source=secret \
>   --set privateCA=true
Error: UPGRADE FAILED: Deployment.apps "rancher" is invalid: [spec.template.spec.volumes[0].secret.defaultMode: Invalid value: 750: must be a number between 0 and 0777 (octal), both inclusive, spec.template.spec.containers[0].volumeMounts[0].name: Not found: "tls-ca-volume"]

**Comment by jgreat** [comment]
Confirmed.

**Comment by jgreat** [comment]
Closing this issue in favor of tracking in rancher/rancher#16053
